-- Asking somebody for their birthday when they do not have the app.
--
-- Decided September 6, 2026. The existing link needs the friend to send
-- something back, which works but is a step people drop. This lets them fill
-- in a form and press submit, and the birthday waits in an inbox until the
-- person who asked next opens Birthed.
--
-- That is a real change to what this product stores, and it is the only place
-- in Birthed where one person's data passes through the server on the way to
-- another person. The privacy page says so in those words. Three things keep
-- it honest:
--
--   1. It is a queue, not a record. The app deletes a reply the moment it has
--      it, and nothing keeps a copy.
--   2. A request expires. After that the code is dead, replies to it are
--      refused, and the whole row goes.
--   3. Only the person who asked can read the replies to their own code.
--
-- No push notifications. The app collects when it is opened, which is enough
-- for a birthday that is at worst a year away, and it means Birthed still has
-- no server that sends anything to anybody's phone.

create table if not exists birthday_requests (
  -- Short enough to read out, long enough not to be guessed. Generated by the
  -- app, which is also the only thing that can create one.
  code        text        primary key check (length(code) between 6 and 24),
  owner_id    uuid        not null default auth.uid(),
  created_at  timestamptz not null default now(),
  expires_at  timestamptz not null default now() + interval '14 days'
);

create index if not exists birthday_requests_owner_idx on birthday_requests (owner_id);
create index if not exists birthday_requests_expiry_idx on birthday_requests (expires_at);

-- Somebody's answer, waiting to be collected. Deliberately not a person: no
-- identifier, no note, no account, nothing linking it to whoever typed it.
create table if not exists birthday_replies (
  id          bigserial   primary key,
  code        text        not null references birthday_requests (code) on delete cascade,
  name        text        not null check (length(trim(name)) between 1 and 60),
  birth_month smallint    not null check (birth_month between 1 and 12),
  birth_day   smallint    not null check (birth_day between 1 and 31),
  birth_year  smallint             check (birth_year between 1900 and 2100),
  created_at  timestamptz not null default now()
);

create index if not exists birthday_replies_code_idx on birthday_replies (code);

alter table birthday_requests enable row level security;
alter table birthday_replies  enable row level security;

-- Only ever your own. Nobody can list codes, which is what stops somebody
-- walking the table and reading other people's answers.
create policy own_birthday_requests on birthday_requests
  for select to authenticated using (owner_id = auth.uid());
create policy open_a_birthday_request on birthday_requests
  for insert to authenticated with check (owner_id = auth.uid());
create policy close_a_birthday_request on birthday_requests
  for delete to authenticated using (owner_id = auth.uid());

-- Replies are readable and deletable only by whoever owns the code they are
-- against. There is deliberately no insert policy: the web form cannot write
-- here directly and goes through the function below instead.
create policy read_my_birthday_replies on birthday_replies
  for select to authenticated using (
    exists (
      select 1 from birthday_requests r
      where r.code = birthday_replies.code and r.owner_id = auth.uid()
    )
  );
create policy delete_my_birthday_replies on birthday_replies
  for delete to authenticated using (
    exists (
      select 1 from birthday_requests r
      where r.code = birthday_replies.code and r.owner_id = auth.uid()
    )
  );

/**
 * Somebody answering the question, from a browser, with no account.
 *
 * A function rather than an insert policy, because an anonymous client that
 * can write to a table can write to it as fast as it likes. This checks the
 * code is real and alive, caps how many answers one code can hold, and gives
 * back nothing at all, so it cannot be used to find out whether a code exists.
 * The caller gets the same answer either way.
 *
 * Sweeping expired requests here rather than on a schedule keeps this to one
 * moving part. Every submission tidies a little, which is enough for a table
 * this size and means nothing has to be installed to run it.
 */
create or replace function leave_birthday(
  request_code text,
  person_name  text,
  month        int,
  day          int,
  year         int default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  alive boolean;
begin
  -- Checked here rather than left to the column constraints, because a
  -- constraint raises and a raise is an answer. Every bad input has to come
  -- back looking exactly like a good one, or the endpoint becomes a way of
  -- asking whether a code exists.
  if person_name is null or length(trim(person_name)) = 0
     or month is null or month < 1 or month > 12
     or day is null or day < 1 or day > 31 then
    return;
  end if;

  delete from birthday_requests where expires_at < now();

  select true into alive
  from birthday_requests
  where code = request_code and expires_at >= now()
  limit 1;

  if alive is null then
    return;
  end if;

  -- One code is one question asked of a group chat, not a mailing list.
  if (select count(*) from birthday_replies where code = request_code) >= 50 then
    return;
  end if;

  insert into birthday_replies (code, name, birth_month, birth_day, birth_year)
  values (
    request_code,
    left(trim(person_name), 60),
    month,
    day,
    case when year between 1900 and 2100 then year else null end
  );
end;
$$;

revoke all on function leave_birthday(text, text, int, int, int) from public;
grant execute on function leave_birthday(text, text, int, int, int) to anon, authenticated;

-- Keeping a link alive.
--
-- A code that dies after a fortnight is right for a code nobody is using and
-- wrong for one sitting in a group chat that people answer over a month. The
-- app pushes the expiry out every time it hands the link to the share sheet,
-- so a link stays good for as long as its owner keeps offering it and dies on
-- its own once they stop.
create policy extend_a_birthday_request on birthday_requests
  for update to authenticated
  using (owner_id = auth.uid())
  with check (owner_id = auth.uid());

/**
 * A ceiling on that, because the client picks the date.
 *
 * Nothing stops a client sending expires_at of the year 3000 and turning a
 * queue into a permanent store of other people's birthdays. This clamps every
 * write, so the longest anything can live is a fortnight from whenever it was
 * last touched, whatever anybody asks for.
 */
create or replace function clamp_birthday_request_expiry()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.expires_at is null or new.expires_at > now() + interval '14 days' then
    new.expires_at := now() + interval '14 days';
  end if;
  return new;
end;
$$;

drop trigger if exists clamp_birthday_request_expiry on birthday_requests;
create trigger clamp_birthday_request_expiry
  before insert or update on birthday_requests
  for each row execute function clamp_birthday_request_expiry();
